name: todo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  get: 4.6.6
  get_storage: ^2.1.1
  flutter_easyloading: 3.0.5
  dotted_border: 2.1.0
  step_progress_indicator: 1.0.2
  intl: 0.19.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 3.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

